# Level 02 CI - Scheduled Execution

# pipeline name
name: 'N2 - Scheduled Execution'

# triggers - workflow start rules
# manual trigger = workflow_dispatch
# scheduled trigger = schedule
# cron format: https://crontab.guru/
# example: "0 0 * * *" = every day at midnight

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes

# tasks inside the pipeline = jobs

jobs:
  # job name
  e2e-tests:
    # machine where the job runs
    runs-on: ubuntu-latest

    # job steps
    steps:
      # clone the repository
      - uses: actions/checkout@v4

      # install Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      # install Yarn
      - name: Installing Yarn
        run: npm install -g yarn

      # install dependencies
      - name: Installing dependencies
        run: yarn

      # install Playwright browsers
      - name: Installing Playwright Browsers
        run: yarn playwright install

      # run e2e tests
      - name: Running e2e tests
        run: yarn run e2e
