# Level 03 CI - Triggered after another pipeline completes

# pipeline name
name: 'N3 - Post-Deploy Execution'

# triggers - workflow start rules
# manual trigger = workflow_dispatch
# scheduled trigger = schedule
# trigger on completion of another workflow = workflow_run

on:
  workflow_run:
    workflows: ['N1 - Manual Execution', 'Scheduled Execution']
    types:
      - completed

# tasks inside the pipeline = jobs

jobs:
  # job name
  e2e-tests:
    # machine where the job runs
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # job steps
    steps:
      # clone the repository
      - uses: actions/checkout@v4

      # install Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      # install Yarn
      - name: Installing Yarn
        run: npm install -g yarn

      # install dependencies
      - name: Installing dependencies
        run: yarn

      # install Playwright browsers
      - name: Installing Playwright Browsers
        run: yarn playwright install

      # run e2e tests
      - name: Running e2e tests
        run: yarn run e2e
